### ISSUE TITLE
Python 2 support

### ISSUE THREAD

**Issue by onyb** [ryukinix/decorating#3]
Trying to run the `animated` decorator example on Python 2, froze my machine. Any plans to support older versions of Python?

**Comment by ryukinix** [comment]
Well, as expected, I put on classifiers whose don't has support for python2. Is really **rare** I use python 2, but I can figured out in soon! Maybe can be simple, because is not so complex yet. You receive any traceback or just frozen your machine? Probably is something related with the `threading` lib. Any info can be useful.

If the people wants support python 2, I can do. You wants. Maybe in the `v0.4` release I try this!

**Comment by onyb** [comment]
@ryukinix No tracebacks.  Machine got unresponsive completely.

If I understand correctly, the intent of this repo is to be a hub for useful Python decorators. It would be great to support multiple Python versions, Python 2.6+ in the least.

**Comment by ryukinix** [comment]
Yes, you are completly right. I will add this feature (support python2) 
on todo.

On 05/20/2016 04:48 PM, Anirudha Bose wrote:

> @ryukinix https://github.com/ryukinix No tracebacks. Machine got 
> unresponsive completely.
> 
> If I understand correctly, the intent of this repo is to be a hub for 
> useful Python decorators. It would be great to support multiple Python 
> versions, Python 2.6+ in the least.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub 
> https://github.com/ryukinix/decorating/issues/3#issuecomment-220701741

## 

As lembranças não são só do passado. Podem ser de agora e até de amanhã.
— Serial Experiments Lain
Manoel Vilela,
Discente em Engenharia da Computação[UFPA] - Turma 2014.
